### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by lafloride** [dcavins/hierarchical-groups-for-bp#1]
Hi David,

I am very glad for this new plugin because the old Group Hierarchy plugin is not supported anymore. Thanks so much!

I just played with your plugin and noticed that I can not select any parent groups when I create a new group. It says that "there are no parent groups available" (although there are several). When I then go on and try to create a hierarchy under the group's manage settings on the fronted I can now select a parent group but it now makes the group go invisible. The sub-group does not show up anymore anywhere. In the directory it shows the correct number of groups but the sub group does not show anymore. Even on the backend the sub-group disappeared but the direct link is still accessible.

Thanks.

WP 4.6.1/BP 2.7.2/Boss theme 2.3.0

**Comment by dcavins** [comment]
Hi @lafloride- 

Thanks for giving this plugin a test drive. It's still very much in development, and your feedback helped me find things to fix.

I hadn't revisited the parent selection portion of the plugin, but made some changes just now that should help the user understand what is going on. Please test out the most recent code and let me know if it makes more sense. (The issue is that not all users will have the same list of possible parents to choose from, so my change makes it easier to see what the current parent is and also to keep the existing choice, even if you can't specifically choose it.)

Re your second problem, I'm pretty sure the problem was a typo that caused the `last activity` group meta item to be deleted if you chose `inherit global setting` for the meta setting
`hgbp-include-activity-from-relatives`. Then the group is no longer considered to be "active" and BuddyPress pretty well ignores it. This is fixed.

Thanks again for reporting the issues you found, and let me know what you find in the future.

-David

**Comment by lafloride** [comment]
Thanks so much. Yes, it works smooth now. Very nice! 

The only thing I don't understand is why I can't select any of the groups I am Group Admin of as a parent during the creation process of a new group. Just a minute later I can just successfully do that from the new group's manage settings. During the creation process however I can only keep the new group as a top level group although I am admin of several other groups.

**Comment by dcavins** [comment]
Hi @lafloride-

Thanks for your new bug report! I've addressed it with this commit: https://github.com/dcavins/hierarchical-groups-for-bp/commit/361d73545f52d2af496ccd7baad58dda6ab16569

Let me know if it solves the problem for you.

Thanks!

-David

**Comment by lafloride** [comment]
Yes, that solved it. Works like a charm. Thanks so much!!
